---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/tflint --version
    register: tflint_test_output
  - debug:
      msg: '{{ tflint_test_output.stdout }}'
