---
- name: Testing andrewrothstein.tflint
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'tflint --version'
      ansible.builtin.command: /usr/local/bin/tflint --version
      changed_when: false
      register: tflint_test_output
    - name: Output from 'tflint --version'
      ansible.builtin.debug:
        msg: '{{ tflint_test_output.stdout }}'
