---
- include_role:
    name: andrewrothstein.unarchivedeps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: look for install in {{ tflint_install_dir }}
  become: true
  stat:
    path: '{{ tflint_install_dir }}'
  changed_when: false
  register: tflint_binary
- when: not tflint_binary.stat.exists
  block:
    - name: downloading {{ tflint_url }}
      become: true
      become_user: root
      get_url:
        url: '{{ tflint_url }}'
        dest: '{{ tflint_tmp_zip }}'
        mode: 0644
        checksum: '{{ tflint_checksum }}'
    - name: mkdir {{ tflint_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ tflint_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive to {{ tflint_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ tflint_tmp_zip }}'
        dest: '{{ tflint_install_dir }}'
        creates: '{{ tflint_exe }}'
  always:
    - name: rm {{ tflint_tmp_zip }}
      become: true
      become_user: root
      file:
        path: '{{ tflint_tmp_zip }}'
        state: absent
- name: link {{ tflint_link }} to {{ tflint_exe }}
  become: true
  become_user: root
  file:
    src: '{{ tflint_exe }}'
    dest: '{{ tflint_link }}'
    state: link
